=== akenza-io/device-type-library/lib/meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/akenza-io/device-type-library/tree/main/types/meta.schema.json",
  "type": "object",
  "title": "meta.json schema",
  "description": "Describes the format of the meta.json",
  "examples": [
    {
      "name": "Elsys - ERS Desk",
      "version": "1.0.0",
      "manufacturer": "Elsys",
      "url": "https://www.elsys.se/shop/product/ers-desk/",
      "description": "Indoor LoRaWAN® device for measuring the indoor environment and desk occupancy",
      "author": "Akenza AG",
      "firmwareVersion": "V1.0.0",
      "availableSensors": [
        "Occupancy",
        "Temperature",
        "Humidity",
        "Light"
      ],
      "outputTopics": [
        "default",
        "occupancy"
      ],
      "encoding": "HEX",
      "connectivity": "LORA"
    }
  ],
  "required": [
    "name",
    "version",
    "manufacturer",
    "author",
    "outputTopics",
    "encoding",
    "connectivity"
  ],
  "properties": {
    "name": {
      "type": "string",
      "title": "The name schema",
      "description": "Device type display name.",
      "examples": [
        "Elsys - ERS Desk"
      ]
    },
    "version": {
      "type": "string",
      "title": "The device type version schema",
      "description": "The version of the device type (schemas + script).",
      "pattern": "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?$",
      "examples": [
        "1.0.0"
      ]
    },
    "manufacturer": {
      "type": "string",
      "title": "The manufacturer schema",
      "description": "Device manufacturer name.",
      "examples": [
        "Elsys"
      ]
    },
    "url": {
      "type": "string",
      "title": "The url schema",
      "description": "URL of the device.",
      "examples": [
        "https://www.elsys.se/shop/product/ers-desk/"
      ]
    },
    "description": {
      "type": "string",
      "title": "The description schema",
      "description": "Short device overview.",
      "examples": [
        "Indoor LoRaWAN® device for measuring the indoor environment and desk occupancy"
      ]
    },
    "author": {
      "type": "string",
      "title": "The author schema",
      "description": "Author of the device type.",
      "examples": [
        "Akenza AG"
      ]
    },
    "firmwareVersion": {
      "type": "string",
      "title": "The firmwareVersion schema",
      "description": "Firmware version reported by the device.",
      "pattern": "^V([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?$",
      "examples": [
        "V1.0.0"
      ]
    },
    "availableSensors": {
      "type": "array",
      "title": "The availableSensors schema",
      "description": "List of sensors the device provides.",
      "examples": [
        [
          "Occupancy",
          "Temperature"
        ]
      ],
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "outputTopics": {
      "type": "array",
      "title": "The outputTopics schema",
      "description": "Topics the device publishes (e.g., default, lifecycle).",
      "default": [
        "default"
      ],
      "examples": [
        [
          "default",
          "occupancy"
        ]
      ],
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "encoding": {
      "type": "string",
      "title": "The encoding schema",
      "description": "Payload encoding format.",
      "enum": [
        "HEX",
        "JSON"
      ],
      "examples": [
        "HEX"
      ]
    },
    "connectivity": {
      "type": "string",
      "title": "The connectivity schema",
      "description": "Network technology used by the device.",
      "enum": [
        "LORA",
        "Sigfox",
        "MQTT",
        "HTTP",
        "NB-IOT",
        "MIOTY"
      ],
      "examples": [
        "LORA"
      ]
    }
  }
}

=== akenza-io/device-type-library/types/disruptiveTechnologies/temperature/meta.json
{
  "name": "Wireless Temperature Sensor",
  "version": "1.0.0",
  "manufacturer": "Disruptive Technologies",
  "url": "https://www.disruptive-technologies.com/products/wireless-sensors/wireless-temperature-sensor",
  "description": "Measures the temperature in any space or on any surface. The temperature sensor is versatile and can enable dozens of applications, from desk occupancy and cold storage to energy efficiency and sustainability.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Temperature",
    "Touch"
  ],
  "outputTopics": [
    "default",
    "touch",
    "network_status",
    "lifecycle"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/disruptiveTechnologies/contact/meta.json
{
  "name": "Wireless Contact Sensor",
  "version": "1.0.0",
  "manufacturer": "Disruptive Technologies",
  "url": "https://www.disruptive-technologies.com/products/wireless-sensors/wireless-proximity-sensor",
  "description": "The Wireless Contact Sensor can detect objects that are removed or placed in front of the sensor. In addition to periodic heartbeats every 15 minutes, the sensor transmits a message when an object is removed or placed in front of the sensor.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Contact",
    "Touch"
  ],
  "outputTopics": [
    "contact",
    "door_count",
    "touch",
    "network_status",
    "lifecycle",
    "washroom_usage"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/dragino/dds20-lb/meta.json
{
  "name": "DDS20-LB",
  "version": "1.0.0",
  "manufacturer": "Dragino",
  "url": "https://www.dragino.com/products/distance-level-sensor/item/273-dds20-lb-ls.html",
  "description": "The Dragino DDS20-LB is a LoRaWAN Ultrasonic liquid level sensor. It uses none-contact method to measure the height of liquid in a container without opening the container.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Distance"
  ],
  "outputTopics": [
    "default",
    "lifecycle",
    "configuration"
  ],
  "encoding": "HEX",
  "connectivity": "LORA"
}

=== akenza-io/device-type-library/types/episensor/episensor/meta.json
{
  "name": "Episensor",
  "version": "1.0.0",
  "manufacturer": "Episensor",
  "url": "https://episensor.com/",
  "description": "Episensor connector",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Power"
  ],
  "outputTopics": [
    "default",
    "error"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/internal/deviceSimulator/meta.json
{
  "name": "Device Simulator",
  "version": "1.0.0",
  "manufacturer": "Akenza",
  "url": "https://docs.akenza.io/device-simulator",
  "description": "The Device Simulator allows you to send data to your HTTP device on akenza without the need for a physical device.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Temperature",
    "Humidity",
    "CO2",
    "Sound",
    "Light",
    "Occupancy"
  ],
  "outputTopics": [
    "default"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/yosensi/YO-Distance/meta.json
{
  "name": "YO Distance",
  "version": "1.0.0",
  "manufacturer": "Yosensi",
  "url": "https://www.yosensi.io/products/yo_distance/",
  "description": "YO Distance is a LoRaWAN device for ultrasonic distance measurement.",
  "author": "Maciej Sacewicz",
  "firmwareVersion": "V3.6.5",
  "availableSensors": [
    "Temperature",
    "Humidity",
    "Distance",
    "Accelerometer - XYZ"
  ],
  "outputTopics": [
    "battery_voltage",
    "internal_temperature",
    "humidity",
    "accelerometer",
    "distance"
  ],
  "encoding": "HEX",
  "connectivity": "LORA"
}

=== akenza-io/device-type-library/types/airthings/cloudConnector/meta.json
{
  "name": "Airthings Cloud Connector",
  "version": "1.0.0",
  "manufacturer": "Airthings",
  "url": "https://www.airthings.com/en/",
  "description": "Airthings Cloud Connector",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Temperature",
    "Humidity",
    "Pressure",
    "CO2",
    "Rel. Lighting",
    "Sound",
    "PM1.0",
    "PM2.5",
    "PM10",
    "Occupancy",
    "Radon",
    "Ventilation",
    "Virus risk",
    "Mold risk"
  ],
  "outputTopics": [
    "airly",
    "environment",
    "lifecycle",
    "mold",
    "occupancy",
    "radon",
    "ventilation",
    "virus"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/adeunis/pulse4/meta.json
{
  "name": "Pulse",
  "version": "1.0.0",
  "manufacturer": "Adeunis",
  "url": "https://www.adeunis.com/en/produit/pulse-impulse-interface/",
  "description": "Meter flow rate monitoring from water, gas and electricity meters. Up to 2 connectable meters. Detection of tampers and leaks.",
  "author": "Akenza AG",
  "firmwareVersion": "V4.0.0",
  "availableSensors": [
    "Flow"
  ],
  "outputTopics": [
    "default",
    "lifecycle",
    "extra"
  ],
  "encoding": "HEX",
  "connectivity": "LORA"
}
