=== akenza-io/device-type-library/lib/meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/akenza-io/device-type-library/tree/main/types/meta.schema.json",
  "type": "object",
  "title": "meta.json schema",
  "description": "Describes the format of the meta.json",
  "examples": [
    {
      "name": "Elsys - ERS Desk",
      "version": "1.0.0",
      "manufacturer": "Elsys",
      "url": "https://www.elsys.se/shop/product/ers-desk/",
      "description": "Indoor LoRaWAN® device for measuring the indoor environment and desk occupancy",
      "author": "Akenza AG",
      "firmwareVersion": "V1.0.0",
      "availableSensors": [
        "Occupancy",
        "Temperature",
        "Humidity",
        "Light"
      ],
      "outputTopics": [
        "default",
        "occupancy"
      ],
      "encoding": "HEX",
      "connectivity": "LORA"
    }
  ],
  "required": [
    "name",
    "version",
    "manufacturer",
    "author",
    "outputTopics",
    "encoding",
    "connectivity"
  ],
  "properties": {
    "name": {
      "type": "string",
      "title": "The name schema",
      "description": "Device type display name.",
      "examples": [
        "Elsys - ERS Desk"
      ]
    },
    "version": {
      "type": "string",
      "title": "The device type version schema",
      "description": "The version of the device type (schemas + script).",
      "pattern": "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?$",
      "examples": [
        "1.0.0"
      ]
    },
    "manufacturer": {
      "type": "string",
      "title": "The manufacturer schema",
      "description": "Device manufacturer name.",
      "examples": [
        "Elsys"
      ]
    },
    "url": {
      "type": "string",
      "title": "The url schema",
      "description": "URL of the device.",
      "examples": [
        "https://www.elsys.se/shop/product/ers-desk/"
      ]
    },
    "description": {
      "type": "string",
      "title": "The description schema",
      "description": "Short device overview.",
      "examples": [
        "Indoor LoRaWAN® device for measuring the indoor environment and desk occupancy"
      ]
    },
    "author": {
      "type": "string",
      "title": "The author schema",
      "description": "Author of the device type.",
      "examples": [
        "Akenza AG"
      ]
    },
    "firmwareVersion": {
      "type": "string",
      "title": "The firmwareVersion schema",
      "description": "Firmware version reported by the device.",
      "pattern": "^V([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?$",
      "examples": [
        "V1.0.0"
      ]
    },
    "availableSensors": {
      "type": "array",
      "title": "The availableSensors schema",
      "description": "List of sensors the device provides.",
      "examples": [
        [
          "Occupancy",
          "Temperature"
        ]
      ],
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "outputTopics": {
      "type": "array",
      "title": "The outputTopics schema",
      "description": "Topics the device publishes (e.g., default, lifecycle).",
      "default": [
        "default"
      ],
      "examples": [
        [
          "default",
          "occupancy"
        ]
      ],
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "encoding": {
      "type": "string",
      "title": "The encoding schema",
      "description": "Payload encoding format.",
      "enum": [
        "HEX",
        "JSON"
      ],
      "examples": [
        "HEX"
      ]
    },
    "connectivity": {
      "type": "string",
      "title": "The connectivity schema",
      "description": "Network technology used by the device.",
      "enum": [
        "LORA",
        "Sigfox",
        "MQTT",
        "HTTP",
        "NB-IOT",
        "MIOTY"
      ],
      "examples": [
        "LORA"
      ]
    }
  }
}

=== akenza-io/device-type-library/types/axis/peopleCounter/meta.json
{
  "name": "People Counter",
  "version": "1.0.0",
  "manufacturer": "Axis",
  "url": "https://www.axis.com/products/axis-people-counter",
  "description": "AXIS People Counter provides actionable insights to evaluate site performance. It counts people in both directions in real-time through compatible ceiling-mounted Axis cameras, automatically disregarding things like strollers and carts. This scalable, server-free application turns your camera into an advanced sensor, and you can expand coverage by connecting two cameras or defining specific counting areas.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "People Counting"
  ],
  "outputTopics": [
    "line_count"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/asystom/sentinel/meta.json
{
  "name": "Sentinel",
  "version": "1.0.0",
  "manufacturer": "Asystom",
  "url": "https://www.asystom.com/solutions/asystomsentinel",
  "description": "The Asystom Sentinel sensor allows with its integrated vibration and ultrasound sensors to accurately detect all kinds of equipment drifts. It also includes ambient temperature monitoring, surface temperature monitoring and optional external sensors.",
  "author": "Akenza AG",
  "firmwareVersion": "V4.57.0",
  "availableSensors": [
    "Humidity",
    "Temperature",
    "Vibration",
    "Frequency",
    "RPM",
    "Shock"
  ],
  "outputTopics": [
    "default",
    "environment",
    "firmware_version",
    "scheduling_settings",
    "advanced_settings",
    "firmware_status"
  ],
  "encoding": "HEX",
  "connectivity": "LORA"
}

=== akenza-io/device-type-library/types/monnit/threePhaseCurrentMeter/meta.json
{
  "name": "Monnit",
  "version": "1.0.0",
  "manufacturer": "Wireless Three-Phase Current Meters",
  "url": "https://www.monnit.com/products/sensors/wireless-three-phase-current-meters/",
  "description": "Wireless current monitoring meter. Available as 20, 150, and 500-amp industrial-grade devices.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Current"
  ],
  "outputTopics": [
    "lifecycle",
    "default",
    "gateway"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/xovis/PC2SV5/meta.json
{
  "name": "PC2S V5",
  "version": "1.0.0",
  "manufacturer": "Xovis",
  "url": "https://www.xovis.com/en/products/detail/pc2s/",
  "description": "Xovis PC2S is a high-precision stereo camera for people counting of the second generation matching the DSGVO. It offers the possibility of evaluating 99 counting lines and 99 counting zones for each sensor. Several meters can simply be interconnected to cover larger areas. The counting works independently, no PC is required for operation.",
  "author": "Akenza AG",
  "firmwareVersion": "V5.0.0",
  "availableSensors": [
    "People Counting"
  ],
  "outputTopics": [
    "count",
    "face_mask",
    "gender",
    "lifecycle",
    "line_count",
    "tag",
    "track",
    "view_direction",
    "zone",
    "queue",
    "queue_time"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/disruptiveTechnologies/co2/meta.json
{
  "name": "Wireless CO2 Sensor",
  "version": "1.0.0",
  "manufacturer": "Disruptive Technologies",
  "url": "https://www.disruptive-technologies.com/products/wireless-co2-sensor",
  "description": "Measures the CO2, temperature, humidity, and barometric pressure in any space.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "CO2",
    "Humidity",
    "Temperature",
    "Pressure"
  ],
  "outputTopics": [
    "co2",
    "default",
    "lifecycle",
    "network_status",
    "pressure"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/vergeSense/cloudConnector/meta.json
{
  "name": "VergeSense Cloud Connector",
  "version": "1.0.0",
  "manufacturer": "VergeSense",
  "url": "https://www.vergesense.com/",
  "description": "This device monitors desk and small room occupancy. Easily mounted directly onto surfaces, no drilling required.",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": [
    "Motion",
    "Occupancy"
  ],
  "outputTopics": [
    "occupancy",
    "space_availability",
    "area_count",
    "floor_count"
  ],
  "encoding": "JSON",
  "connectivity": "HTTP"
}

=== akenza-io/device-type-library/types/advantech/BB-WSW2C00015/meta.json
{
  "name": "Advantech - BB-WSW2C00015",
  "version": "1.0.0",
  "manufacturer": "Advantech",
  "url": "https://www.advantech.com/products/",
  "description": "Industrial LoRaWAN node equipped with an RS485 interface for Modbus RTU sensor integration.",
  "author": "Akenza AG",
  "availableSensors": [
    "Modbus"
  ],
  "outputTopics": [
    "modbus",
    "system"
  ],
  "encoding": "HEX",
  "connectivity": "LORA"
}

=== akenza-io/device-type-library/types/GWF/GWFcoder/meta.json
{
  "name": "RCM®-LRW10",
  "version": "1.0.0",
  "manufacturer": "GWF",
  "url": "https://gwf.ch/en/produkt/gwfcoder-radio-module-lorawan/",
  "description": "Simple readout of water and gas meters with GWFcoder® registers without necessity to access buildings",
  "author": "Akenza AG",
  "firmwareVersion": "V1.0.0",
  "availableSensors": ["Water", "Gas", "Volume"],
  "outputTopics": ["default", "lifecycle"],
  "encoding": "HEX",
  "connectivity": "LORA"
}
